# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            ToiDB
tagline:          'Full-Stack developer'
description:      "Hi, I'm a Full-Stack Developer and Rubyist :D"
url:              http://toidang.xyz
baseurl:          /

comments: true

author:
  name:           'Bá Tới'
  url:            https://www.facebook.com/toidang3011

paginate:         3
