# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            ToiDB
tagline:          'Full-Stack developer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://toidang.xyz
baseurl:          /

author:
  name:           'Bá Tới'
  url:            https://www.facebook.com/toidang3011

paginate:         5

# Custom vars
version:          2.1.0
